version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/create-table.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data:
